# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cf933683abbd7143bfc1866575bb76dce477c3ed5f303c2a3a8e1fd8bd19396b3541ec5a27d84ab31cebb0ad33d262cdc1fb4d79a7ac386b30b57bb782801a78

test:
  secret_key_base: d2d48e831953e34964b8adb612681dd0fde38a9f1b5aed38f37f760009cd8e001fcc6286e784adf7da5fdef057a851b034314473703c8e153c88948d00a53587

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
